# Markdown renderer configuration
[goldmark.renderer]
unsafe = false

[tableOfContents]
endLevel = 4
ordered = true
startLevel = 2

[highlight]
anchorLineNos = true
codeFences = true
guessSyntax = false
hl_Lines = ''
hl_inline = false
lineAnchors = ''
lineNoStart = 1
lineNos = true
lineNumbersInTable = true
noClasses = true
noHl = false
style = 'onedark'
tabWidth = 4
