# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: LRH3321's Blog
subtitle: Bug制造者
description: 常年挖坑不填
keywords:
author: LRH3321
language: zh-CN
timezone: Asia/Shanghai

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://www.lrh3321.win/
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives/
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:
  - "README.md"
  - "robots.txt"

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: true
  tab_replace: false
  wrap: true
  hljs: true

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

archive_generator:
  per_page: 8
  yearly: true
  monthly: true
  daily: false

category_generator:
  per_page: 5

tag_generator:
  per_page: 5
  enable_index_page: false

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## Use post's date for updated date unless set in front-matter
updated_option: mtime

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include: []
exclude: []
ignore:
 - README.md

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: theme-next

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: heroku
  repo: git@github.com:lrh3321/lrh3321.github.io.git
  message: "Site updated: {{ now('YYYY-MM-DD HH:mm:ss') }}"

#################################################################
###################### NexT Configuration #######################
#################################################################

theme_config:
  # ---------------------------------------------------------------
  # Theme Core Configuration Settings
  # See: https://theme-next.js.org/docs/theme-settings/
  # ---------------------------------------------------------------

  # Define custom file paths.
  # Create your custom files in site directory `source/_data` and uncomment needed files below.
  custom_file_path:
    #head: source/_data/head.njk
    #header: source/_data/header.njk
    #sidebar: source/_data/sidebar.njk
    #postMeta: source/_data/post-meta.njk
    #postBodyEnd: source/_data/post-body-end.njk
    #footer: source/_data/footer.njk
    #bodyEnd: source/_data/body-end.njk
    variable: source/_data/variables.styl
    #mixin: source/_data/mixins.styl
    style: source/_data/styles.styl

  footer:
    # Specify the date when the site was setup. If not defined, current year will be used.
    since: 2017

  # ---------------------------------------------------------------
  # Scheme Settings
  # ---------------------------------------------------------------

  # Schemes
  # scheme: Muse
  #scheme: Mist
  #scheme: Pisces
  scheme: Gemini

  # Dark Mode
  darkmode: true


  # ---------------------------------------------------------------
  # Menu Settings
  # ---------------------------------------------------------------

  # Usage: `Key: /link/ || icon`
  # Key is the name of menu item. If the translation for this item is available, the translated text will be loaded, otherwise the Key name will be used. Key is case-senstive.
  # Value before `||` delimiter is the target link, value after `||` delimiter is the name of Font Awesome icon.
  # When running the site in a subdirectory (e.g. yoursite.com/blog), remove the leading slash from link value (/archives -> archives).
  # External url should start with http:// or https://
  menu:
    home: / || fa fa-home
    #about: /about/ || fa fa-user
    tags: /tags/ || fa fa-tags
    categories: /categories/ || fa fa-th
    archives: /archives/ || fa fa-archive
    #schedule: /schedule/ || fa fa-calendar
    #sitemap: /sitemap.xml || fa fa-sitemap
    #commonweal: /404/ || fa fa-heartbeat

  # Enable / Disable menu icons / item badges.
  menu_settings:
    icons: true
    badges: true

  # Social Links
  # Usage: `Key: permalink || icon`
  # Key is the link label showing to end users.
  # Value before `||` delimiter is the target permalink, value after `||` delimiter is the name of Font Awesome icon.
  social:
    GitHub: https://github.com/lrh3321 || fab fa-github
    E-Mail: mailto:lrh3321@gmail.com || fa fa-envelope
    Weibo: https://weibo.com/lrh3321 || fab fa-weibo
    #Google: https://plus.google.com/yourname || fab fa-google
    #Twitter: https://twitter.com/yourname || fab fa-twitter
    #FB Page: https://www.facebook.com/yourname || fab fa-facebook
    #StackOverflow: https://stackoverflow.com/yourname || fab fa-stack-overflow
    #YouTube: https://youtube.com/yourname || fab fa-youtube
    #Instagram: https://instagram.com/yourname || fab fa-instagram
    #Skype: skype:yourname?call|chat || fab fa-skype
    Coding: https://coding.net/u/lrh3321 || fas fa-code
    LeetCode: https://leetcode.com/lrh3321/ || fas fa-code

  # Mermaid tag
  mermaid:
    enable: true
    # Available themes: default | dark | forest | neutral
    theme: forest

# Live2D
## https://github.com/EYHN/hexo-helper-live2d
live2d:
  enable: true
  scriptFrom: local
  pluginRootPath: live2dw/
  pluginJsPath: lib/
  pluginModelPath: assets/
  tagMode: false
  debug: false
  model:
    use: "/live2dw/asuna/asuna_04.model.json"
    # use: "https://cdn.jsdelivr.net/npm/live2d-widget-model-chitose@latest/assets/chitose.model.json"
    # use: "https://cdn.jsdelivr.net/npm/live2d-widget-model-epsilon2_1@latest/assets/Epsilon2.1.model.json"
    # use: "https://cdn.jsdelivr.net/npm/live2d-widget-model-gf@latest/assets/Gantzert_Felixander.model.json"
    # use: "https://cdn.jsdelivr.net/npm/live2d-widget-model-haruto@latest/assets/haruto.model.json"
    # use: "https://cdn.jsdelivr.net/npm/live2d-widget-model-hibiki@latest/assets/hibiki.model.json"
    # use: "https://cdn.jsdelivr.net/npm/live2d-widget-model-hijiki@latest/assets/hijiki.model.json"
    # use: "https://cdn.jsdelivr.net/npm/live2d-widget-model-izumi@latest/assets/izumi.model.json"
    # use: "https://cdn.jsdelivr.net/npm/live2d-widget-model-koharu@latest/assets/koharu.model.json"
    # use: "https://cdn.jsdelivr.net/npm/live2d-widget-model-miku@latest/assets/miku.model.json"
    # use: "https://cdn.jsdelivr.net/npm/live2d-widget-model-ni-j@latest/assets/ni-j.model.json"
    # use: "https://cdn.jsdelivr.net/npm/live2d-widget-model-nico@latest/assets/nico.model.json"
    # use: "https://cdn.jsdelivr.net/npm/live2d-widget-model-nietzsche@latest/assets/nietzsche.model.json"
    # use: "https://cdn.jsdelivr.net/npm/live2d-widget-model-nipsilon@latest/assets/nipsilon.model.json"
    # use: "https://cdn.jsdelivr.net/npm/live2d-widget-model-nito@latest/assets/nito.model.json"
    # use: "https://cdn.jsdelivr.net/npm/live2d-widget-model-shizuku@latest/assets/shizuku.model.json"
    # use: "https://cdn.jsdelivr.net/npm/live2d-widget-model-tororo@latest/assets/tororo.model.json"
    # use: "https://cdn.jsdelivr.net/npm/live2d-widget-model-tsumiki@latest/assets/tsumiki.model.json"
    # use: "https://cdn.jsdelivr.net/npm/live2d-widget-model-unitychan@latest/assets/unitychan.model.json"
    # use: "https://cdn.jsdelivr.net/npm/live2d-widget-model-wanko@latest/assets/wanko.model.json"
    # use: "https://cdn.jsdelivr.net/npm/live2d-widget-model-z16@latest/assets/z16.model.json"
    # use: "https://cdn.jsdelivr.net/npm/live2d-widget-model-haru@1.0.5/01/assets/haru01.model.json"
    # use: "https://cdn.jsdelivr.net/npm/live2d-widget-model-haru@1.0.5/02/assets/haru02.model.json"
  display:
    position: right
    width: 300
    height: 600
  mobile:
    show: true
  react:
    opacity: 0.7
