# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: LRH3321's Blog
subtitle: Bug制造者
description: 常年挖坑不填
keywords:
author: LRH3321
language: zh-CN
timezone: Asia/Shanghai

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://www.lrh3321.win/
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives/
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:
  - "README.md"
  - "robots.txt"

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: true
  tab_replace: false
  wrap: true
  hljs: true

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

archive_generator:
  per_page: 8
  yearly: true
  monthly: true
  daily: false

category_generator:
  per_page: 5

tag_generator:
  per_page: 5
  enable_index_page: false

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## Use post's date for updated date unless set in front-matter
use_date_for_updated: false

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include: []
exclude: []
ignore:
 - README.md

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: theme-next

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: heroku
  repo: git@github.com:lrh3321/lrh3321.github.io.git
  message: "Site updated: {{ now('YYYY-MM-DD HH:mm:ss') }}"

#################################################################
###################### NexT Configuration #######################
#################################################################

theme_config:
  # ---------------------------------------------------------------
  # Theme Core Configuration Settings
  # See: https://theme-next.js.org/docs/theme-settings/
  # ---------------------------------------------------------------

  # Define custom file paths.
  # Create your custom files in site directory `source/_data` and uncomment needed files below.
  custom_file_path:
    #head: source/_data/head.njk
    #header: source/_data/header.njk
    #sidebar: source/_data/sidebar.njk
    #postMeta: source/_data/post-meta.njk
    #postBodyEnd: source/_data/post-body-end.njk
    #footer: source/_data/footer.njk
    #bodyEnd: source/_data/body-end.njk
    variable: source/_data/variables.styl
    #mixin: source/_data/mixins.styl
    style: source/_data/styles.styl

  footer:
    # Specify the date when the site was setup. If not defined, current year will be used.
    since: 2017

    # Icon between year and copyright info.
    icon:
      # Icon name in Font Awesome. See: https://fontawesome.com/icons
      name: fa fa-heart
      # If you want to animate the icon, set it to true.
      animated: false
      # Change the color of icon, using Hex Code.
      color: "#ff0000"

    # If not defined, `author` from Hexo `_config.yml` will be used.
    copyright:

    # Powered by Hexo & NexT
    powered: true


  # ---------------------------------------------------------------
  # Scheme Settings
  # ---------------------------------------------------------------

  # Schemes
  # scheme: Muse
  #scheme: Mist
  #scheme: Pisces
  scheme: Gemini

  # Dark Mode
  darkmode: true


  # ---------------------------------------------------------------
  # Menu Settings
  # ---------------------------------------------------------------

  # Usage: `Key: /link/ || icon`
  # Key is the name of menu item. If the translation for this item is available, the translated text will be loaded, otherwise the Key name will be used. Key is case-senstive.
  # Value before `||` delimiter is the target link, value after `||` delimiter is the name of Font Awesome icon.
  # When running the site in a subdirectory (e.g. yoursite.com/blog), remove the leading slash from link value (/archives -> archives).
  # External url should start with http:// or https://
  menu:
    home: / || fa fa-home
    #about: /about/ || fa fa-user
    tags: /tags/ || fa fa-tags
    categories: /categories/ || fa fa-th
    archives: /archives/ || fa fa-archive
    #schedule: /schedule/ || fa fa-calendar
    #sitemap: /sitemap.xml || fa fa-sitemap
    #commonweal: /404/ || fa fa-heartbeat

  # Enable / Disable menu icons / item badges.
  menu_settings:
    icons: true
    badges: true

  # Social Links
  # Usage: `Key: permalink || icon`
  # Key is the link label showing to end users.
  # Value before `||` delimiter is the target permalink, value after `||` delimiter is the name of Font Awesome icon.
  social:
    GitHub: https://github.com/lrh3321 || fab fa-github
    E-Mail: mailto:lrh3321@gmail.com || fa fa-envelope
    Weibo: https://weibo.com/lrh3321 || fab fa-weibo
    #Google: https://plus.google.com/yourname || fab fa-google
    #Twitter: https://twitter.com/yourname || fab fa-twitter
    #FB Page: https://www.facebook.com/yourname || fab fa-facebook
    #StackOverflow: https://stackoverflow.com/yourname || fab fa-stack-overflow
    #YouTube: https://youtube.com/yourname || fab fa-youtube
    #Instagram: https://instagram.com/yourname || fab fa-instagram
    #Skype: skype:yourname?call|chat || fab fa-skype
    Coding: https://coding.net/u/lrh3321 || fas fa-code
    LeetCode: https://leetcode.com/lrh3321/ || fas fa-code

  codeblock:
    # Code Highlight theme
    # See: https://github.com/highlightjs/highlight.js/tree/master/src/styles
    theme:
      light: default
      dark: tomorrow-night-eighties
    # See: https://github.com/PrismJS/prism/tree/master/themes
    prism:
      light: prism
      dark: prism-tomorrow
    # Add copy button on codeblock
    copy_button:
      enable: true
      # Available values: default | flat | mac
      style: flat


  # ---------------------------------------------------------------
  # Font Settings
  # See: https://theme-next.js.org/docs/theme-settings/#Fonts-Customization
  # ---------------------------------------------------------------
  # Find fonts on Google Fonts (https://www.google.com/fonts)
  # All fonts set here will have the following styles:
  #   light | light italic | normal | normal italic | bold | bold italic
  # Be aware that setting too much fonts will cause site running slowly
  # ---------------------------------------------------------------
  # To avoid space between header and sidebar in scheme Pisces / Gemini, Web Safe fonts are recommended for `global` (and `title`):
  # Arial | Tahoma | Helvetica | Times New Roman | Courier New | Verdana | Georgia | Palatino | Garamond | Comic Sans MS | Trebuchet MS
  # ---------------------------------------------------------------

  font:
    enable: false
    host: //fonts.lug.ustc.edu.cn

    # Font options:
    # `external: true` will load this font family from `host` above.
    # `family: Times New Roman`. Without any quotes.
    # `size: x.x`. Use `em` as unit. Default: 1 (16px)

    # Global font settings used for all elements inside <body>.
    global:
      external: true
      family: Lato
      size:

    # Font settings for site title (.site-title).
    title:
      external: true
      family:
      size:

    # Font settings for headlines (<h1> to <h6>).
    headings:
      external: true
      family:
      size:

    # Font settings for posts (.post-body).
    posts:
      external: true
      family:

    # Font settings for <code> and code blocks.
    codes:
      external: true
      family: Fira Code


  # ---------------------------------------------------------------
  # Third Party Plugins & Services Settings
  # See: https://theme-next.js.org/docs/third-party-services/
  # More plugins: https://github.com/next-theme/awesome-next
  # You may need to install dependencies or set CDN URLs in `vendors`
  # There are two different CDN providers by default:
  #   - jsDelivr (cdn.jsdelivr.net), works everywhere even in China
  #   - CDNJS (cdnjs.cloudflare.com), provided by cloudflare
  # ---------------------------------------------------------------

  # Math Formulas Render Support
  # Server-side plugin: https://github.com/next-theme/hexo-filter-mathjax
  math:
    # Default (true) will load mathjax / katex script on demand.
    # That is it only render those page which has `mathjax: true` in Front-matter.
    # If you set it to false, it will load mathjax / katex srcipt EVERY PAGE.
    per_page: true

    # hexo-renderer-pandoc (or hexo-renderer-kramed) required for full MathJax support.
    mathjax:
      enable: true
      # See: https://mhchem.github.io/MathJax-mhchem/
      mhchem: false

    # hexo-renderer-markdown-it-plus (or hexo-renderer-markdown-it with markdown-it-katex plugin) required for full Katex support.
    katex:
      enable: true
      # See: https://github.com/KaTeX/KaTeX/tree/master/contrib/copy-tex
      copy_tex: true

  # Mermaid tag
  mermaid:
    enable: true
    # Available themes: default | dark | forest | neutral
    theme: forest


  #! ---------------------------------------------------------------
  #! DO NOT EDIT THE FOLLOWING SETTINGS
  #! UNLESS YOU KNOW WHAT YOU ARE DOING
  #! See: https://theme-next.org/docs/advanced-settings
  #! ---------------------------------------------------------------

  # Script Vendors. Set a CDN address for the vendor you want to customize.
  # Be aware that you would better use the same version as internal ones to avoid potential problems.
  # Remember to use the https protocol of CDN files when you enable https on your site.
  vendors:
    # Internal path prefix.
    _internal: lib

    # Internal version: 3.1.0
    anime: //cdn.jsdelivr.net/npm/animejs@3.1.0/lib/anime.min.js
    # anime:

    # Internal version: 5.13.0
    fontawesome: //cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@5/css/all.min.css
    # fontawesome: //cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/css/all.min.css
    # fontawesome:

    # Prism
    prism: //cdn.jsdelivr.net/npm/prismjs@1/components/prism-core.min.js
    prism_autoloader: //cdn.jsdelivr.net/npm/prismjs@1/plugins/autoloader/prism-autoloader.min.js
    prism_line_numbers: //cdn.jsdelivr.net/npm/prismjs@1/plugins/line-numbers/prism-line-numbers.js
    # prism:
    # prism_autoloader:
    # prism_line_numbers:

    # MathJax
    mathjax: //cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
    # mathjax:

    # KaTeX
    katex: //cdn.jsdelivr.net/npm/katex@0/dist/katex.min.css
    # katex: //cdnjs.cloudflare.com/ajax/libs/KaTeX/0.11.1/katex.min.css
    copy_tex_js: //cdn.jsdelivr.net/npm/katex@0/dist/contrib/copy-tex.min.js
    copy_tex_css: //cdn.jsdelivr.net/npm/katex@0/dist/contrib/copy-tex.min.css
    # katex:
    # copy_tex_js:
    # copy_tex_css:

    # Internal version: 0.2.8
    pjax: //cdn.jsdelivr.net/gh/theme-next/theme-next-pjax@0/pjax.min.js
    # pjax:

    # FancyBox
    jquery: //cdn.jsdelivr.net/npm/jquery@3/dist/jquery.min.js
    fancybox: //cdn.jsdelivr.net/gh/fancyapps/fancybox@3/dist/jquery.fancybox.min.js
    fancybox_css: //cdn.jsdelivr.net/gh/fancyapps/fancybox@3/dist/jquery.fancybox.min.css
    # jquery:
    # fancybox:
    # fancybox_css:

    # Medium-zoom
    mediumzoom: //cdn.jsdelivr.net/npm/medium-zoom@1/dist/medium-zoom.min.js
    # mediumzoom:

    # Lazyload
    lazyload: //cdn.jsdelivr.net/npm/lozad@1/dist/lozad.min.js
    # lazyload: //cdnjs.cloudflare.com/ajax/libs/lozad.js/1.9.0/lozad.min.js
    # lazyload:

    # Pangu
    pangu: //cdn.jsdelivr.net/npm/pangu@4/dist/browser/pangu.min.js
    # pangu: //cdnjs.cloudflare.com/ajax/libs/pangu/4.0.7/pangu.min.js
    # pangu:

    # Quicklink
    quicklink: //cdn.jsdelivr.net/npm/quicklink@1/dist/quicklink.umd.js
    # quicklink:

    # DisqusJS
    disqusjs_js: //cdn.jsdelivr.net/npm/disqusjs@1/dist/disqus.js
    disqusjs_css: //cdn.jsdelivr.net/npm/disqusjs@1/dist/disqusjs.css
    # disqusjs_js:
    # disqusjs_css:

    # Valine
    valine: //cdn.jsdelivr.net/npm/valine@1/dist/Valine.min.js
    # valine: //cdnjs.cloudflare.com/ajax/libs/valine/1.3.10/Valine.min.js
    # valine:

    # Gitalk
    gitalk_js: //cdn.jsdelivr.net/npm/gitalk@1/dist/gitalk.min.js
    gitalk_css: //cdn.jsdelivr.net/npm/gitalk@1/dist/gitalk.css
    # gitalk_js:
    # gitalk_css:

    # Algolia Search
    algolia_search: //cdn.jsdelivr.net/npm/algoliasearch@4/dist/algoliasearch-lite.umd.js
    instant_search: //cdn.jsdelivr.net/npm/instantsearch.js@4/dist/instantsearch.production.min.js
    # algolia_search:
    # instant_search:

    # PDF
    pdfobject: //cdn.jsdelivr.net/npm/pdfobject@2/pdfobject.min.js
    # pdfobject: //cdnjs.cloudflare.com/ajax/libs/pdfobject/2.1.1/pdfobject.min.js
    # pdfobject:

    # Mermaid
    mermaid: //cdn.jsdelivr.net/npm/mermaid@8/dist/mermaid.min.js
    # mermaid: //cdnjs.cloudflare.com/ajax/libs/mermaid/8.4.8/mermaid.min.js
    # mermaid:

    # Internal version: 1.2.1
    velocity: //cdn.jsdelivr.net/npm/velocity-animate@1/velocity.min.js
    # velocity: //cdnjs.cloudflare.com/ajax/libs/velocity/1.2.1/velocity.min.js
    velocity_ui: //cdn.jsdelivr.net/npm/velocity-animate@1/velocity.ui.min.js
    # velocity_ui: //cdnjs.cloudflare.com/ajax/libs/velocity/1.2.1/velocity.ui.min.js
    # velocity:
    # velocity_ui:

    # Internal version: 1.0.2
    pace: //cdn.jsdelivr.net/npm/pace-js@1/pace.min.js
    # pace: //cdnjs.cloudflare.com/ajax/libs/pace/1.0.2/pace.min.js
    pace_css: //cdn.jsdelivr.net/npm/pace-js@1/themes/blue/pace-theme-minimal.css
    # pace_css: //cdnjs.cloudflare.com/ajax/libs/pace/1.0.2/themes/blue/pace-theme-minimal.min.css
    # pace:
    # pace_css:

    # Internal version: 1.0.0
    three: //cdn.jsdelivr.net/gh/theme-next/theme-next-three@1/three.min.js
    three_waves: //cdn.jsdelivr.net/gh/theme-next/theme-next-three@1/three-waves.min.js
    canvas_lines: //cdn.jsdelivr.net/gh/theme-next/theme-next-three@1/canvas_lines.min.js
    canvas_sphere: //cdn.jsdelivr.net/gh/theme-next/theme-next-three@1/canvas_sphere.min.js
    # three:
    # three_waves:
    # canvas_lines:
    # canvas_sphere:

    # Internal version: 1.0.0
    canvas_nest: //cdn.jsdelivr.net/gh/theme-next/theme-next-canvas-nest@1/canvas-nest.min.js
    canvas_nest_nomobile: //cdn.jsdelivr.net/gh/theme-next/theme-next-canvas-nest@1/canvas-nest-nomobile.min.js
    # canvas_nest:
    # canvas_nest_nomobile:

    # Internal version: 1.0.0
    canvas_ribbon: //cdn.jsdelivr.net/gh/theme-next/theme-next-canvas-ribbon@1/canvas-ribbon.js
    # canvas_ribbon:

  # Assets
  css: css
  js: js
  images: images

# Live2D
## https://github.com/EYHN/hexo-helper-live2d
live2d:
  enable: true
  scriptFrom: local
  pluginRootPath: live2dw/
  pluginJsPath: lib/
  pluginModelPath: assets/
  tagMode: false
  debug: false
  model:
    use: "/live2dw/asuna/asuna_04.model.json"
    # use: "https://cdn.jsdelivr.net/npm/live2d-widget-model-chitose@latest/assets/chitose.model.json"
    # use: "https://cdn.jsdelivr.net/npm/live2d-widget-model-epsilon2_1@latest/assets/Epsilon2.1.model.json"
    # use: "https://cdn.jsdelivr.net/npm/live2d-widget-model-gf@latest/assets/Gantzert_Felixander.model.json"
    # use: "https://cdn.jsdelivr.net/npm/live2d-widget-model-haruto@latest/assets/haruto.model.json"
    # use: "https://cdn.jsdelivr.net/npm/live2d-widget-model-hibiki@latest/assets/hibiki.model.json"
    # use: "https://cdn.jsdelivr.net/npm/live2d-widget-model-hijiki@latest/assets/hijiki.model.json"
    # use: "https://cdn.jsdelivr.net/npm/live2d-widget-model-izumi@latest/assets/izumi.model.json"
    # use: "https://cdn.jsdelivr.net/npm/live2d-widget-model-koharu@latest/assets/koharu.model.json"
    # use: "https://cdn.jsdelivr.net/npm/live2d-widget-model-miku@latest/assets/miku.model.json"
    # use: "https://cdn.jsdelivr.net/npm/live2d-widget-model-ni-j@latest/assets/ni-j.model.json"
    # use: "https://cdn.jsdelivr.net/npm/live2d-widget-model-nico@latest/assets/nico.model.json"
    # use: "https://cdn.jsdelivr.net/npm/live2d-widget-model-nietzsche@latest/assets/nietzsche.model.json"
    # use: "https://cdn.jsdelivr.net/npm/live2d-widget-model-nipsilon@latest/assets/nipsilon.model.json"
    # use: "https://cdn.jsdelivr.net/npm/live2d-widget-model-nito@latest/assets/nito.model.json"
    # use: "https://cdn.jsdelivr.net/npm/live2d-widget-model-shizuku@latest/assets/shizuku.model.json"
    # use: "https://cdn.jsdelivr.net/npm/live2d-widget-model-tororo@latest/assets/tororo.model.json"
    # use: "https://cdn.jsdelivr.net/npm/live2d-widget-model-tsumiki@latest/assets/tsumiki.model.json"
    # use: "https://cdn.jsdelivr.net/npm/live2d-widget-model-unitychan@latest/assets/unitychan.model.json"
    # use: "https://cdn.jsdelivr.net/npm/live2d-widget-model-wanko@latest/assets/wanko.model.json"
    # use: "https://cdn.jsdelivr.net/npm/live2d-widget-model-z16@latest/assets/z16.model.json"
    # use: "https://cdn.jsdelivr.net/npm/live2d-widget-model-haru@1.0.5/01/assets/haru01.model.json"
    # use: "https://cdn.jsdelivr.net/npm/live2d-widget-model-haru@1.0.5/02/assets/haru02.model.json"
  display:
    position: right
    width: 300
    height: 600
  mobile:
    show: true
  react:
    opacity: 0.7
