# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: LRH3321's Blog
subtitle: Bug制造者
description: 常年挖坑不填
author: LRH3321
language: zh-CN
timezone: Asia/Shanghai

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://www.lrh3321.win/
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives/
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang

skip_render:
  - "robots.txt"

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: true
  tab_replace: false

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)

index_generator:
  per_page: 4
  order_by: -date

archive_generator:
  per_page: 8
  yearly: true
  monthly: true
  daily: false

category_generator:
  per_page: 5

tag_generator:
  per_page: 5
  enable_index_page: false

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: next

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: heroku
  repo: git@github.com:lrh3321/lrh3321.github.io.git
  message: "Site updated: {{ now('YYYY-MM-DD HH:mm:ss') }}"

#################################################################
###################### NexT Configuration #######################
#################################################################

theme_config:
  # ============================================================= #
  # ============= Theme Core Configuration Settings ============= #
  # ============================================================= #

  cache:
    enable: true

  reminder: true

  custom_file_path:
    style: source/_data/styles.styl
    # footer: source/_data/footer.swig
  menu:
    home: / || home
    #about: /about/ || user
    tags: /tags/ || tags
    categories: /categories/ || th
    archives: /archives/ || archive
    #schedule: /schedule/ || calendar
    #sitemap: /sitemap.xml || sitemap
    #commonweal: /404/ || heartbeat
  scheme: Gemini
  social:
    GitHub: https://github.com/lrh3321 || github
    E-Mail: mailto:lrh3321@gmail.com || envelope
    Weibo: https://weibo.com/lrh3321 || weibo
    Coding: https://coding.net/u/lrh3321
    #Google: https://plus.google.com/yourname || google
    #Twitter: https://twitter.com/yourname || twitter
    #FB Page: https://www.facebook.com/yourname || facebook
    #VK Group: https://vk.com/yourname || vk
    #StackOverflow: https://stackoverflow.com/yourname || stack-overflow
    #YouTube: https://youtube.com/yourname || youtube
    #Instagram: https://instagram.com/yourname || instagram
    #Skype: skype:yourname?call|chat || skype
  # Post edit
  # Dependencies: https://github.com/hexojs/hexo-deployer-git
  post_edit:
    enable: false
    url: https://github.com/lrh3321/lrh3321.github.io/edit/blog-source/source/_posts/ # Link for view source.
    #url: https://github.com/user-name/repo-name/edit/branch-name/subdirectory-name # Link for fork & edit.

  font:
    host: //fonts.lug.ustc.edu.cn
    # Font settings for <code> and code blocks.
    codes:
      external: true
      family: Fira Code

  # Mermaid tag
  mermaid:
    enable: false
    # Available themes: default | dark | forest | neutral
    theme: forest
    cdn: //cdn.jsdelivr.net/npm/mermaid@8/dist/mermaid.min.js
    #cdn: //cdnjs.cloudflare.com/ajax/libs/mermaid/8.0.0/mermaid.min.js

# Live2D
## https://github.com/EYHN/hexo-helper-live2d
live2d:
  enable: true
  scriptFrom: local
  pluginRootPath: live2dw/
  pluginJsPath: lib/
  pluginModelPath: assets/
  tagMode: false
  debug: false
  model:
    # use: "https://cdn.jsdelivr.net/npm/live2d-widget-model-chitose@latest/assets/chitose.model.json"
    # use: "https://cdn.jsdelivr.net/npm/live2d-widget-model-epsilon2_1@latest/assets/Epsilon2.1.model.json"
    # use: "https://cdn.jsdelivr.net/npm/live2d-widget-model-gf@latest/assets/Gantzert_Felixander.model.json"
    # use: "https://cdn.jsdelivr.net/npm/live2d-widget-model-haruto@latest/assets/haruto.model.json"
    # use: "https://cdn.jsdelivr.net/npm/live2d-widget-model-hibiki@latest/assets/hibiki.model.json"
    # use: "https://cdn.jsdelivr.net/npm/live2d-widget-model-hijiki@latest/assets/hijiki.model.json"
    # use: "https://cdn.jsdelivr.net/npm/live2d-widget-model-izumi@latest/assets/izumi.model.json"
    # use: "https://cdn.jsdelivr.net/npm/live2d-widget-model-koharu@latest/assets/koharu.model.json"
    # use: "https://cdn.jsdelivr.net/npm/live2d-widget-model-miku@latest/assets/miku.model.json"
    # use: "https://cdn.jsdelivr.net/npm/live2d-widget-model-ni-j@latest/assets/ni-j.model.json"
    # use: "https://cdn.jsdelivr.net/npm/live2d-widget-model-nico@latest/assets/nico.model.json"
    # use: "https://cdn.jsdelivr.net/npm/live2d-widget-model-nietzsche@latest/assets/nietzsche.model.json"
    # use: "https://cdn.jsdelivr.net/npm/live2d-widget-model-nipsilon@latest/assets/nipsilon.model.json"
    # use: "https://cdn.jsdelivr.net/npm/live2d-widget-model-nito@latest/assets/nito.model.json"
    # use: "https://cdn.jsdelivr.net/npm/live2d-widget-model-shizuku@latest/assets/shizuku.model.json"
    # use: "https://cdn.jsdelivr.net/npm/live2d-widget-model-tororo@latest/assets/tororo.model.json"
    # use: "https://cdn.jsdelivr.net/npm/live2d-widget-model-tsumiki@latest/assets/tsumiki.model.json"
    # use: "https://cdn.jsdelivr.net/npm/live2d-widget-model-unitychan@latest/assets/unitychan.model.json"
    use: "https://cdn.jsdelivr.net/npm/live2d-widget-model-wanko@latest/assets/wanko.model.json"
    # use: "https://cdn.jsdelivr.net/npm/live2d-widget-model-z16@latest/assets/z16.model.json"
    # use: "https://cdn.jsdelivr.net/npm/live2d-widget-model-haru@1.0.5/01/assets/haru01.model.json"
    # use: "https://cdn.jsdelivr.net/npm/live2d-widget-model-haru@1.0.5/02/assets/haru02.model.json"
  display:
    position: right
    width: 150
    height: 300
  mobile:
    show: true
  react:
    opacity: 0.7
